stages:
  - sonarcloud

sonarcloud_scan:
  image: node:16
  stage: sonarcloud
  variables:
    SONAR_TOKEN: $SONAR_TOKEN
  script:
    - npm install
    - npx sonar-scanner \
        -Dsonar.projectKey=theasherah \
        -Dsonar.organization=theasherah \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$SONAR_TOKEN